language: node_js
node_js:
  - "stable"
  - "5.0"
  - "4.0"
sudo: false

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

cache:
  directories:
    - node_modules
